### PR TITLE
Features implemented

### PR DESCRIPTION
**Pull request by ghighi-du63000**
# Vertical Scrolling is there Booyah !
Comming with many options 
Issue #1 (vert. scrolling) corrected.
# Function added
* self.chg_size
* self.update *(change an image into another or just change size)*
* rem *(remove an image from the "database")

Update #2 done

### CODE REVIEW

**Comment by forslund** [comment]
Thanks for the pull request. I'll look it over a and merge it when I get the time. I might do a few changes before the merge.

There are a lot changes of the indentation (4 blank spaces to tab), next time you make a pull request to the project try to use the same style.

Once more, thanks for your help and interest in the project.

**Comment by forslund** [comment]
One more thing, can you give a use case for how the update and chg_size methods are intended to be used?

**Comment by forslund** [comment]
I removed the left/right and top/bottom options since I think they add too much complexity without introducing anything new. You can reverse the direction by setting a negative speed as it is at the moment.

Thanks for the contribution! Contributers Rock!

**Comment by ghighi-du63000** [comment]
It's all right.

I'm sorry for style changes, it's just that I always code with tabs. (Hahaha endless dilema btw tabs/spaces)

Do you still need the use case ?

Date: Mon, 16 Feb 2015 12:07:05 -0800

**Comment by forslund** [comment]
After looking at your paper plane-game I think I've understood the methods so I don't need the use cases.

**Pull request merged**
