### PR TITLE
cloud layer no longer moves + improvements to demo.py and demo file structure

### PR DESCRIPTION
**Pull request by cheffley6**
#### Description
Demo: Cloud layer `scroll_speed` is now set to `math.inf` in order to demonstrate how to add a layer that doesn't move at all. Added a `MODE` setting to allow automatic panning left or right in addition to manually panning with arrow keys. Added a few comments for explaining code, and renamed variables for clarity.

File structure: Renamed image files to describe the images. Renamed `demo` folder to `images`. Moved `demo.py` to top-level folder in order to run the demo without any changes required (I'm using MacOS, but let me know if this change breaks compatibility on other platforms).

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [ ] Bugfix
- [x] Feature implementation
- [ ] Refactor of code (without functional changes)
- [x] Documentation improvements
- [ ] Test improvements

#### Testing
Tested manually on MacOS to verify implementation behaves as expected. Used Mojave, Python 3.9.1, and pygame 2.0.2.

#### Documentation
Some comments added to `demo.py`.

### CODE REVIEW

**Comment by cheffley6** [comment]
let me know if any changes need to be rolled back @forslund - hopefully i didn't go overboard with renaming/comments.

also, is it just that my 2015 Mac is too old and slow, or does the scroll speed seem to be a bit inconsistent when 640x480 is the resolution? was wondering if there was anything that could be done about the processing speed, but I haven't looked at parallax.py enough to be able to say whether the implementation causes any latency beyond that of pygame.

**Comment by forslund** [comment]
On my 2016 HP laptop the problem with the demo is that is a bit too fast (didn't want to add complexity to lock the speed to keep the demo simple) so I'm not sure why it would be slow on your Mac :/

I'd like to keep the demo in a selfcontained folder to keep the root of the project clean,  apart from that I have no issues with the changes

**Comment by cheffley6** [comment]
Updated to set the file structure as needed.

In order to still run `demo/demo.py` I had to append `../` to `sys.path` in `demo.py`.

Should it be mentioned in the docs that the user needs to be in the `demo` directory for `demo.py` to recognize the `parallax` module?

**Comment by forslund** [comment]
You don't need to do that, I'm adding some instructions to the readme but basically you can run `python3 -m demo.demo` to run it from the root folder of the repo

**Comment by cheffley6** [comment]
ohh got it, i'm used to just running `python3 demo.py` but that works too. i think a note in the readme would be helpful

**Comment by cheffley6** [comment]
added instructions to the readme. lmk if any other changes are needed 🙂

**Comment by forslund** [comment]
Super nice! I'll squash and merge this. Thank you

**Pull request merged**
